# Generated by Django 4.2.1 on 2023-06-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mentorsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('NOT_SELECTED', 'Not Selected'), ('ENROLLED', 'Enrolled'), ('PASSED', 'Passed'), ('DROPPED', 'Dropped')], max_length=50),
        ),
    ]
