# Generated by Django 4.2.1 on 2023-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PASSED', 'Passed'), ('DROPPED', 'Dropped')], max_length=50),
        ),
    ]
